version: "3"
services:
  # nginx
  nginx:
    depends_on: # 依赖于服务 php
      - php
    build: ./nginx
    #image: nginx:1.14.2-alpine
    ports:
      - "80:80"
      - "81:81" # 宿主:容器
      - "82:82" # 宿主:容器
      - "83:83" # 宿主:容器
    volumes:
      - /data/web/www/docker.lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf # 配置文件
      - /data/web/www/docker.lnmp/nginx/conf.d:/etc/nginx/conf.d # 配置文件
      - /data/web/www/docker.lnmp/nginx/log:/var/log/nginx # 日志文件
      - /data/web/www:/var/www/html
    restart: always
    environment:
      TZ: Asia/Shanghai
    container_name: long-nginx
    networks:
      - lnmp-net
  # php-7.3
  php:
    depends_on:
      - mysql
      - redis
    #image: tinywan/dnmp:php7.2-v1
    build: ./php
    environment:
      # fastdfs
      IP: 172.17.0.16
      FDFS_PORT: 22122
    ports:
      - "9000:9000"
    volumes:
      - /data/web/www:/var/www/html
      - /data/web/www/docker.lnmp/php/log/:/var/log/php/:rw
      - /data/web/www/docker.lnmp/php/php.ini:/usr/local/etc/php/php.ini
      - /data/web/www/docker.lnmp/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - /data/web/www/docker.lnmp/php/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
    networks:
      - lnmp-net
    container_name: long-php # 容器名称
  # mysql 5.7
  mysql:
    #image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password #覆盖容器启动后默认执行的命令
    build: ./mysql # 使用Dockerfile文件
    hostname: long-mysql
    ports:
      - "3306:3306"
    volumes:
      - /data/web/mysql:/var/lib/mysql # mysql 数据文件
      - /data/web/www/docker.lnmp/mysql/my.cnf:/etc/mysql/my.cnf # mysql 配置文件
      - /data/web/www/docker.lnmp/mysql/log:/var/log/mysql:rw # mysql 日志
    environment:
      MYSQL_ROOT_PASSWORD: long
    networks:
      - lnmp-net
    restart: always
    container_name: long-mysql
  # redis
  redis:
    #image: redis:5.0-alpine
    build: ./redis
    hostname: long-redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - lnmp-net
    volumes:
      - /data/web/www/docker.lnmp/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/web/www/docker.lnmp/redis/log/redis.log:/data/log/redis.log
    restart: always
    container_name: long-redis

  # fastdfs
  fastdfs:
    build: ./fastdfs
    ports:
      - "8888:8888"
      - "22122:22122"
      - "23000:23000"
      - "8011:8084"
    networks:
      - lnmp-net # 如果build时连不上网络：docker build --network host ./fastdfs  docker tag 500b941e6f79 php:latest
    environment:
      # 容器环境变量 172.17.0.16
      - FASTDFS_IPADDR=172.17.0.16
    volumes:
      # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
      - /data/web/fastdfs:/home/dfs
      # 配置
      - /data/web/www/docker.lnmp/fastdfs/conf:/etc/fdfs
    container_name: long-fastdfs

networks:
  lnmp-net:
    driver: bridge
  # lnmp-net:
  #   driver: host
