version: '3'

services:
    nginx:
        depends_on:  # 依赖于服务 php
            - php
        build : ./nginx
        #image: nginx:1.14.2-alpine
        ports:
            - "80:80" # 宿主:容器  为了避免与宿主机的 80端口冲突 映射 8080
        volumes:
           - /data/docker.lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf # 配置文件
           - /data/docker.lnmp/nginx/conf.d:/etc/nginx/conf.d  # 配置文件
           - /data/docker.lnmp/nginx/log:/var/log/nginx  # 日志文件
           - /data/web/www:/var/www/html
        restart: always
        environment:
           TZ: Asia/Shanghai  
        container_name: long-nginx
        networks:
            - lnmp-net
    php:
        depends_on:
            - mysql
            - redis
        #image: tinywan/dnmp:php7.2-v1
        build : ./php
        ports:
            - "9000:9000"
        volumes:
            - /data/web/www:/var/www/html
            - /data/docker.lnmp/php/log/:/var/log/php/:rw
            - /data/docker.lnmp/php/php.ini:/usr/local/php/etc/php.ini
            - /data/docker.lnmp/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - /data/docker.lnmp/php/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - lnmp-net    
        container_name: long-php # 容器名称   
    mysql:
        #image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password #覆盖容器启动后默认执行的命令
        build : ./mysql # 使用Dockerfile文件
        hostname: long-mysql
        ports:
            - "3306:3306"
        volumes:
            - /data/web/mysql:/var/lib/mysql # mysql 数据文件
            - /data/docker.lnmp/mysql/my.cnf:/etc/mysql/my.cnf # mysql 配置文件
            - /data/docker.lnmp/mysql/log/:/var/log/mysql/:rw  # mysql 日志
        environment:
            MYSQL_ROOT_PASSWORD: long  
        networks:
            - lnmp-net
        restart: always
        container_name: long-mysql
    redis:
        #image: redis:5.0-alpine
        build : ./redis
        hostname: long-redis
        ports:
            - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf    
        networks:
            - lnmp-net      
        volumes:
            - /data/docker.lnmp/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - /data/docker.lnmp/redis/log/redis.log:/data/redis.log
        restart: always
        container_name: long-redis
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8082:80"
        networks:
            - lnmp-net
        environment:
            - PMA_HOST=long-mysql
            - PMA_PORT=3308
        container_name: long-phpmyadmin
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:latest
        ports:
            - "8083:80"
        networks:
            - lnmp-net
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_PORT=6379
        container_name: long-phpredisadmin
networks:
  lnmp-net:
    driver: bridge   
